### ISSUE TITLE
Add a phrase at the bottom of the page stating where to submit a vocabulary if you want it added.

### ISSUE THREAD

**Issue by dgarijo** [mariapoveda/vocab.linkeddata.es#11]

**Comment by dgarijo** [comment]
I think it would be better to add a servlet for "testing if my vocab is ready to be uploaded".
Then the URI would be sent to Miguel Angel or Raul

**Comment by mariapoveda** [comment]
I was also thinking in adding something like "if it is a vocab build in collaboration with oeg contact vocab@delicias.... otherwise try in LOV?"
