### ISSUE TITLE
search bar

### ISSUE THREAD

**Issue by mariapoveda** [mariapoveda/vocab.linkeddata.es#19]
To include a search function including typeahead that looks in the title of the vocabs.

**Comment by dgarijo** [comment]
This is more a filter by ontology. Extend the filter bar from smartcities.

**Comment by dgarijo** [comment]
Partly fixed in https://github.com/mariapoveda/vocab.linkeddata.es/commit/b8dd21f64ab3b456f13023d1463a3f6796a16347. Will have to add the titles as well
