### ISSUE TITLE
Resources blocking and loading slowly

### ISSUE THREAD

**Issue by alejandrofcarrera** [mariapoveda/vocab.linkeddata.es#41]
In some cases, some resources block the website. The reason is that resources are not exist.

* css/bootstrap-responsive.css
* js/jquery.js

Also, it is important minify the static content and improve async load for SEO.

* js/jquery-1.11.0.js, 50 %
* js/jquery-ui.js, 37 %
* js/bootstrap.js, 27 %
* js/jquery.stickytableheaders.js, 35 %
* css/bootstrap.css, 9 %
* css/jquery-ui.css, 18 %

The last point it is to specify cache time for this resources.

**Comment by dgarijo** [comment]
Removed the non-existing resources.
